### ISSUE TITLE
Key not found exceptions on the read side

### ISSUE THREAD

**Issue by anilca** [aerospike/aerospike-net-extensions#1]
Hi,

We are using the nuget package v1.0.0. On our first attempt we directly added the package to our project and started sending read requests heavily. The default package references directly Aerospike.Client v.3.6.6. We observed `Error Code 2: Key not found`  exceptions time to time.  
Sample exception:

> ExceptionDetail={"Result":-1,"InnerException":{"Result":2,"Message":"Error Code 2: Key not found","InDoubt":false,"Type":"Aerospike.Client.AerospikeException","Source":"AerospikeClient","HResult":-2146233088},"Message":"Error Code -1(inDoubt): Error Code 2: Key not found","InDoubt":true,"Type":"Aerospike.Client.AerospikeException","Source":"System.Private.CoreLib","HResult":-2146233088}
SourceContext=Wayfair.Merlin.Core.Cache.HybridCacheManager
inner_exception_stack_trace=   at Aerospike.Client.AsyncOperate.HandleNotFound(Int32 resultCode)
   at Aerospike.Client.AsyncSingleCommand.ParseCommand()
   at Aerospike.Client.AsyncCommand.ExecuteCommand()
exception_stack_trace=   at Wayfair.Merlin.Core.Cache.HybridCacheManager`1.<>c__DisplayClass6_0.<<Get>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Wayfair.Merlin.Core.Cache.HybridCacheManager`1.Get(String cacheKey)
inner_exception_type=AerospikeException
exception_type=AerospikeException
@version=1
inner_exception_message=Error Code 2: Key not found
exception_message=Error Code -1(inDoubt): Error Code 2: Key not found

Then we tried updating Aerospike.Client version to the latest 4.1. But we are still getting the exception but this time in a different format. 
We handled the exception 11 times in around 45k read requests. Why doesn't it just return null for all the cases that it couldn't find the key? Would you please share your opinion? 
Thanks,

**Comment by BrianNichols** [comment]
It appears that the "Key not found" exception is nested inside another AerospikeException.  Null records are only returned when the top-level exception is "Key not found".  There is one possible place in AsyncCommand where this nested exception could be created, but the stack trace doesn't exactly match up.  Can you provide a debug stack trace where the latest AerospikeClient 4.1.1 is referenced?

If you want to test my hypothesis, can you also clone our latest AerospikeClient repo and insert the following to AsyncCommand.cs, line 229:

```
catch (AerospikeException ae)
{
    ErrorCount++;
    FailOnApplicationError(ae);
}
```

Then, reference this custom client from Aerospike.Extensions.Caching and let us know the results.  If successful, we will release a new C# client with this change.

**Comment by BrianNichols** [comment]
C# client 4.1.2 has been released with the fix:

https://www.aerospike.com/download/client/csharp/notes.html#4.1.2
